 
import { Inter } from 'next/font/google'
//import React,{useState} from "react";

import MenuComponent from "../../components/MenuComponent";
import SideBarUser from "../../components/SideBarUser";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //const [showMenu, setshowMenu] = useState(false);
  return (
    <html lang="en">
      <body  >
      <div className="flex flex-1 w-full h-screen">
     <div className='hidden md:block' >
     <SideBarUser/>
     </div>
      <div className="flex flex-col flex-1">
        <div className="w-full h-[70px] p-4 bg-gray-50 flex shadow-md  items-center justify-end">
        <MenuComponent/>
         <div className="flex items-center"> 
         <p className="mr-4 text-sm">Aboubacar Sidibé</p>
         <picture  className="self-center w-12 h-12 bg-white rounded-full shadow-md md:self-start">
     <img src={"https://picsum.photos/300/200?random=10"} alt="image" className="object-cover w-full h-full rounded-lg rounded-t-lg white" />
     </picture>
        
         </div>
        </div>
        <div className="h-full p-4 overflow-y-scroll md:p-10 ">{children}</div>
      </div>
    </div>
      </body>
    </html>
  )
}
